name: API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/upload-artifact@v4

    - name: Setup Node.js
      uses: actions/upload-artifact@v4
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run API Tests
      run: |
        newman run "API Testing Project - Posts Service.postman_collection.json" -e "QA API Environment.postman_environment.json" -r htmlextra

    - name: Upload Test Report
      uses:  actions/upload-artifact@v4
      with:
        name: test-report
        path: newman/